name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true
      message:
        description: 'Tag message'
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.event.inputs.version }}
      MESSAGE: ${{ github.event.inputs.message }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update image tag
      run: /bin/bash ./hack/update-image-tag.sh $VERSION

    - name: Set git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"

    - name: Commit
      run: |
        git add .
        git commit -m "New version: ${VERSION}"
        git push origin ${GITHUB_REF#refs/heads/}

    - name: Tag
      run: |
        git tag $VERSION -m "$MESSAGE"
        git push origin $VERSION
